### ISSUE TITLE
Could not find controller if controller is a .ts file

### ISSUE THREAD

**Issue by TommyTheTribe** [exegesis-js/exegesis#189]
Hi !

Trying to use exegesis with a .ts file as a controller, got an error :

```
(node:244) UnhandledPromiseRejectionWarning: Error: Could not find controller documents defined in /paths/~1documents~1file~1{id}/get
    at validateController (/app/node_modules/exegesis/src/oas3/Operation.ts:58:19)
    at validateControllers (/app/node_modules/exegesis/src/oas3/Operation.ts:88:9)
    at new Operation (/app/node_modules/exegesis/src/oas3/Operation.ts:151:9)
    at /app/node_modules/exegesis/src/oas3/Path.ts:39:34
    at Array.reduce (<anonymous>)
    at new Path (/app/node_modules/exegesis/src/oas3/Path.ts:38:14)
    at new Paths (/app/node_modules/exegesis/src/oas3/Paths/index.ts:23:32)
    at new OpenApi (/app/node_modules/exegesis/src/oas3/OpenApi.ts:57:23)
    at Object.<anonymous> (/app/node_modules/exegesis/src/oas3/index.ts:18:12)
    at Generator.next (<anonymous>)
```

Is there a way to get it working ?

Thanks a lot !

**Comment by jwalton** [comment]
Hi!  The most likely thing I can think of is that you're [not setting the `controllersPattern` option](https://github.com/exegesis-js/exegesis/blob/master/docs/Options.md#controllers)?  There are [integration tests](https://github.com/exegesis-js/exegesis/tree/master/test/integration/integration) that use .ts controllers, so it definitely should work.  :)

**Comment by TommyTheTribe** [comment]
Oh Missed that one ! Thanks a lot ;)
